#!/bin/bash
if  command -v docker; then
echo " dockeris yra jau "
#sudo systemctl status docker
#sudo docker run hello-world
#sudo docker search centos
#sudo docker pull centos:7
#sudo docker run -t -i centos:7 /bin/bash
#sudo docker ps -a

#sudo docker pull fedora
#sudo docker run -t -i fedora /bin/bash
#sudo docker ps -a
#sudo docker pause kind_dijkstra
#sudo docker unpause kind_dijkstra
#sudo docker stop kind_dijkstra
#sudo docker start kind_dijkstra
#sudo docker delete kind_dijkstra
#sudo docker rm [1 konteinerio vardas] [2 konteinerio vardas]
#sudo docker container prune # viska istrina kas buvo exitintas
#sudo docker rmi centos:7 fedora
#sudo docker  image prune -a 
else
sudo apt update -y 
sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt install -y docker-ce docker-ce-cli containerd.io
docker -v
fi

cat > app.py << "EOF"
from flask import Flask

app = Flask(__name__)

@app.route('/')
def hello_world():
    return 'Hello, World!'

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)
EOF

cat >  requirements.txt <<"REQ"
flask
REQ

cat > Dockerfile <<"DOC"
# Use an official Python runtime as a parent image
FROM python:3.8-slim-buster

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV NAME=World

# Run app.py when the container launches
CMD ["python", "app.py"]
DOC

#sudo docker build -t my-flask-app .
#sudo docker run -d -p 5000:5000 my-flask-app
#curl http://localhost:5000

#sudo apt update
#sudo apt install apache2 -y

curl http://localhost
sudo docker ps
